language: c
sudo: true
before_install:
  - curl -XGET https://nodejs.org/download/nightly/v6.0.0-nightly20160425eb4201f07a/node-v6.0.0-nightly20160425eb4201f07a-linux-x64.tar.gz > /tmp/nightly.tar.gz
  - tar -xvf /tmp/nightly.tar.gz
  - ln -s node-v6.0.0-nightly20160425eb4201f07a-linux-x64/bin/node /usr/local/node
  - ln -s node-v6.0.0-nightly20160425eb4201f07a-linux-x64/bin/npm /usr/local/npm
  - node --version
  - npm --version
install: npm install
script: npm test
